$(document).ready(function(){
    $("#mycarousel").carousel( { interval: 3000 } );
    $("#carouselButton").click(function(){
        if($('#carouselButton').children('span').hasClass('fa fa-pause')){
            $("#mycarousel").carousel('pause');
            $('#carouselButton').children('span').removeClass('fa-pause');
            $('#carouselButton').children('span').addClass('fa-play');
        }
        else{
            $('#mycarousel').carousel('cycle');
            $('#carouselButton').children('span').removeClass('fa-play');
            $('#carouselButton').children('span').addClass('fa-pause');
        }
    });
    $('#loginButton').click(function(){
        $('#loginModal').modal("toggle");
    });
    $('#loginCross').click(function(){
        $('#loginModal').modal("toggle");
    })
    $('#loginCancel').click(function(){
        $('#loginModal').modal("toggle");
    })
    $('#reserveButton').click(function(){
        $('#reserveTableModal').modal("toggle");
    })
    $('#reserveCross').click(function(){
        $('#reserveTableModal').modal("toggle");
    })
    $('#reserveCancel').click(function(){
        $('#reserveTableModal').modal("toggle");
    })
});